spring:
  datasource:
    url: jdbc:mysql://123.207.24.223:3306/mall
    username: mall
    password: Mall@hbitmp162611
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    map-underscore-to-camel-case: true

system:
  auth: false
  wxappid: wxappid
  wxsceret: sceret